# 配置 favicon，目录位于 source 文件夹下
favicon: images/avatar.png

# 顶部菜单
menu:
  主页: /
  关于: about

# 版权说明
copyright:
  name: rtz

# 文章协议
license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# rss
rss:
  path: atom.xml
  # path: rss2.xml

# MathJax
mathjax:
  enable: true
  # cnd: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.min.js

# KaTeX
# 移除默认的渲染器：
# $ npm uninstall hexo-renderer-marked --save
# 安装：
# $ npm install @upupming/hexo-renderer-markdown-it-plus --save
# 安装完成后执行清理命令：
# $ hexo clean
katex:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css

# 评论系统：Utterances
utterances:
  enable: false
  repo: owner/repo
  issueTerm: pathname
  theme: github-light

# 谷歌分析
analytics:
  enable: false
  gtag: G-XXXXXXXXXXXX
